### ISSUE TITLE
Тернарный оператор

### ISSUE THREAD

**Issue by Rim4i4ok** [UliaSivridi/double_elimination#1]
https://github.com/UliaSivridi/double_elimination/blob/c8774b185c5cb28b0da8fc96bf00284177df8f00/double_elimination.js#L19

Т.к. `gridMatch`  булевый, то `===` - лишнее

`var ltr = gridMatch ? 'w' : 'l'; `

**Comment by UliaSivridi** [comment]
Наверно, хотелось сделать код совсем наглядным :) Но тогда можно было бы использовать `==`.
Это если `false`, то надо `===`, чтобы не попасть на `undefined`. А то я сначала пыталась делать `if !(variable)`, а оно не срабатывало.
Окей, поправлю.
